config/routes.rb
FBApps::Application.routes.draw do
  get "password_resets/new"
  resources :users
  resources :teams, only: [:edit, :update, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  # Static routes
  root  'static_pages#home'
  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/help',              to: 'static_pages#help',            via: 'get'
  match '/about',             to: 'static_pages#about',           via: 'get'
  match '/contact',           to: 'static_pages#contact',         via: 'get'
  match 'users/confirm/:confirmation_token', to: 'users#confirm', 
                       as: :confirm,  via: 'get'
  match 'users/resend_confirm/:id',  to: 'users#resend_confirm', 
                       as: :resend_confirm,     via: 'get'
  match 'users/admin_add/:id', to: 'users#admin_add',    
                       as: :admin_add,     via: 'get'
  match 'users/admin_del/:id', to: 'users#admin_del',    
                       as: :admin_del,     via: 'get'


  # Diagnostics paths
  match 'pools/diagnostics/:id',   to: 'pools#pool_diagnostics',   as: :pool_diagnostics,    via: 'get'
  match 'pools/diag_chg/:id',      to: 'pools#pool_diag_chg', as: :pool_diag_chg,    via: 'get'
  match 'seasons/diagnostics/:id', to: 'seasons#season_diagnostics',   as: :season_diagnostics,    via: 'get'
  match 'seasons/diag_chg/:id',    to: 'seasons#season_diag_chg', as: :season_diag_chg,    via: 'get'
  
  # Seasons and weeks paths
  match 'weeks/open/:id',       to: 'weeks#open',        as: :open,          via: 'get'
  match 'weeks/closed/:id',     to: 'weeks#closed',      as: :closed,        via: 'get'
  match 'weeks/final/:id',      to: 'weeks#final',       as: :final,         via: 'get'
  match 'weeks/auto_create',    to: 'weeks#auto_create', as: :auto_create,   via: 'get'
  match 'weeks/add_scores/:id', to: 'weeks#add_scores',  as: :add_scores,    via: 'get'
  match 'seasons/open/:id',     to: 'seasons#open',      as: :season_open,   via: 'get'
  match 'seasons/closed/:id',   to: 'seasons#closed',    as: :season_closed, via: 'get'
  resources :seasons, shallow: :true do
    resources :weeks
  end

  # Pools and Pool Messages routes
  match 'pools/join/:id',     to: 'pools#join',    as: :join,     via: 'get'
  match 'pools/leave/:id',    to: 'pools#leave',   as: :leave,    via: 'get'
  match 'pools/my_pools',     to: 'pools#my_pools',as: :my_pools, via: 'get'
  match 'pools/:id/invite',   to: 'pool_messages#invite',  as: :invite,   via: 'get'
  match 'pools/:id/send_invite',   to: 'pool_messages#send_invite',  as: :send_invite,   via: 'post'
  resources :pools do
    resources :entries, only: [:new, :create]
    resources :pool_messages, only: [:new, :create]
  end
  
  resources :entries, only: [:edit, :update, :destroy] do
    resources :picks, only: [:new, :create]
  end

  resources :weeks, only: [:edit, :update, :show, :destroy]

  resources :picks, only: [:edit, :update, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :signed_in_user
  before_action :confirmed_user
  before_action :admin_user, only: [:pool_diagnostics, :pool_diag_chg ]

  def new
    year = Season.getSeasonYear
    
    # !!!! This code breaks once the college pools are added
    season = Season.where(year: year, nfl_league: true).first
    if season
      @pool = current_user.pools.new
      @pool_edit_flag = false
      current_week = season.getCurrentWeek
      if current_week.checkStateClosed || current_week.checkStateFinal
        @pool.starting_week = current_week.week_number + 1
      else
        @pool.starting_week = current_week.week_number
      end
    else
      flash[:error] = "Cannot create a pool because the #{year} season is not ready for pools!"
      redirect_to_back_or_default(pools_path)
    end
  end

  def create
    # Get either the NFL or college season
    year = Season.getSeasonYear
    if Pool.typeSUP?(pool_params[:poolType])
      season = Season.where(year: year, nfl_league: false).first
    else
      season = Season.where(year: year, nfl_league: true).first
    end
    
    if season && season.isOpen?
      # If the season is setup then create the pool.
      current_week = season.getCurrentWeek
      @pool = current_user.pools.create(pool_params.merge(season_id: season.id))
      if @pool.id
        # create entry for owner of pool
        entry_name = @pool.getEntryName(current_user)
        new_entry_params = { name: entry_name }
        @pool.entries.create(new_entry_params.merge(user_id: current_user.id))
        # Handle a successful save
        flash[:success] = "Pool '#{@pool.name}' was created successfully!"
        # Set the ownership in PoolMembership.owner
        @pool.setOwner(current_user, true)
        redirect_to @pool
      else
        render 'new'
      end
    else
      flash[:error] = "Cannot create a pool because the #{year} season is not ready for pools!"
      redirect_to pools_path
    end
  end

  def join
    # Test to make sure User is not already a member of this pool
    @pool = Pool.find(params[:id])
    if @pool.isMember?(current_user)
      flash[:notice] = "Already a member of Pool '#{@pool.name}'!"
      redirect_to @pool
    else
      if @pool.isOpen?
        @pool.addUser(current_user)
        flash[:success] = "Successfully added to Pool '#{@pool.name}'!"
        redirect_to @pool
      else
        flash[:error] = "Sorry, but the pool is closed. Couldn't be added to Pool '#{@pool.name}'!"
        redirect_to @pool
      end
    end
  end

  def leave
    @pool = Pool.find(params[:id])
    if @pool.isOwner?(current_user)
      flash[:error] = "Owner cannot leave the pool!"
      redirect_to @pool
    elsif !@pool.isMember?(current_user)
      flash[:error] = "Not a member of Pool '#{@pool.name}'!"
      redirect_to pools_path
    else
      if @pool.isOpen?
        @pool.removeUser(current_user)
        flash[:success] = "Successfully removed from Pool '#{@pool.name}'!"
        redirect_to pools_path
      else
        flash[:error] = "Sorry, but the pool is closed. Cannot be removed from Pool '#{@pool.name}'!"
        redirect_to @pool
      end
    end
  end

  def my_pools
    @pools = current_user.pools.paginate(page: params[:page])
  end

  def index
    @pools = Pool.paginate(page: params[:page])
  end

  def show
    @pool = Pool.find(params[:id])
    if @pool.nil?
      flash[:notice] = 'The pool you tried to access does not exist'
      redirect_to pools_path
    else
      @pools = @pool.users.paginate(:page => params[:page])
      @season = Season.find(@pool.season_id)
      @current_week = @pool.getCurrentWeek
    end
  end

  def edit
    @pool = Pool.find(params[:id])
    if @pool
      @season = Season.find(@pool.season.id)
      if @season.getCurrentWeek.week_number > 1
        @pool_edit_limited = true
      else
        @pool_edit_limited = false
      end
      @pool_edit_flag = true
    
      if !@pool.isOwner?(current_user)
        flash[:error] = "Only the owner can edit the pool!"
        redirect_to pools_path
      end
    else
        flash[:error] = "Cannot find Pool with id #{params[:id]}!"
        redirect_to pools_path
    end
  end
  
  def update
    @pool = Pool.find(params[:id])
    if @pool.isOwner?(current_user)
      if @pool.update_attributes(pool_params)
        flash[:success] = "Pool updated."
        redirect_to @pool
      else
        render 'edit'
      end
    else
      flash[:error] = "Only the owner can edit the pool!"
      redirect_to pools_path
    end
  end

  def destroy
    @pool = Pool.find(params[:id])
    if @pool.isOwner?(current_user)
      @pool.remove_memberships
      @pool.recurse_delete
      flash[:success] = "Successfully deleted Pool '#{@pool.name}'!"
      redirect_to pools_path
    else
      flash[:error] = "Only the onwer can delete the pool!"
      redirect_to pools_path
    end
  end

  def pool_diagnostics
    @pool = Pool.find(params[:id])
    if @pool
      @season = Season.find(@pool.season.id)
    else
      flash[:error] = "Cannot find Pool with id #{params[:id]}!"
      redirect_to pools_path
    end
  end

  # This action receives multiple args.  The first is the pool, and the second is the action to do, the third is any other pertinent info
  def pool_diag_chg
    if params[:surv]
      entry = Entry.find(params[:entry_id])
      pool = Pool.find(entry.pool_id)
      if entry.survivorStatusIn
        value = false
      else
        value = true
      end
      entry.update_attribute(:survivorStatusIn, value)
      entry.save
    elsif params[:pool_status]
      pool = Pool.find(params[:pool_id])
      if pool.pool_done
        pool_done = false
      else
        pool_done = true
      end
      pool.update_attribute(:pool_done, pool_done)
      pool.save
    end
    redirect_to pool_diagnostics_path(pool)
  end
  
  private

    def pool_params
      params.require(:pool).permit(:name, :poolType, :allowMulti, 
                                   :isPublic, :starting_week, :password)
    end

    def authenticate
      deny_access unless signed_in?
    end

    # Before filters
    def admin_user
      redirect_to current_user, notice: "Only an Admin User can access that page!" unless current_user.admin?
    end

end

app/views/pools/_entry_mgmt_menu.html.erb
<% if pool.isMember?(current_user) %>
  <li class="menu-item dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" > Manage Entry <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% if pool.allowMulti %>
        <li><%= link_to "Create entry", new_pool_entry_path(pool) %></li>
      <% end %>
      <li class="divider"></li>
      <% entries = pool.entries.where(user_id: current_user.id) %>
      <% entries.each do |entry| %>
        <li class="menu-item dropdown dropdown-submenu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" > <%= entry.name %> </a>
          <ul class="dropdown-menu">
            <li class=menu-item><%= link_to "Edit entry", edit_entry_path(entry) %></li>
            <li class=menu-item>
              <%= link_to "Delete entry", entry, method: :delete,
                  data: {confirm: "Are you sure?"}, title: "Delete#{entry.name}" %>
            </li>
            <% if !current_week.nil? %>
              <% pick = entry.picks.where(week_id: current_week.id) %>
              <% if pick.empty? %>
                <% if entry.survivorStatusIn %>
                  <% if !pool.getSurvivorWinner %>
                    <% if pool.getCurrentWeek.week_number >= pool.starting_week %>
                      <li><%= link_to "Make pick(s)", new_entry_pick_path(entry) %></li>
                    <% end %>
                  <% else %>
                    <li><%= link_to "Pool is done!", "#" %></li>
                  <% end %>
                <% else %>
                  <li><%= link_to "Survivor Status:Out", "#" %></li>
                <% end %>
              <% else %>
                <% if current_week.checkStateOpen %>
                  <% pick = pick[0] %>
                  <li><%= link_to "Edit pick(s)", edit_pick_path(pick) %></li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/pools/_fields.html.erb
  <%= f.error_notification %>

  <%= f.input :name, placeholder: 'Name' %>

<% if nil %>
  <%= f.input :poolType, label: 'Pool Type', placeholder: 'Pool Type', 
              collection: Pool::POOL_TYPES, selected: Pool::POOL_TYPES[:Survivor], disabled: true,
              hint: 'At this time only Survivor pools are supported.' %>
<% end %>
  <%= f.input :poolType, label: 'Pool Type', placeholder: 'Pool Type', 
              collection: Pool::POOL_TYPES, selected: Pool::POOL_TYPES[:Survivor],
              hint: 'At this time only Survivor pools are supported.' %>

  <%= f.input :allowMulti, label: 'Allow Multiple', 
              hint: 'Allow multiple entries per user', as: :radio_buttons  %>
              
  <%= f.input :starting_week, label: 'Starting Week', placeholder: 'Starting Week' %>
  
  
<% if nil %>
  <%= f.input :isPublic, label: 'Public', as: :radio_buttons %>

  <%= f.input :password, placeholder: 'Password' %>
<% end %>

app/views/pools/_my_pool.html.erb
  <tr>
    <td><%= link_to pool.name, pool %></td>
    <td><%= render 'show_type', :pool => pool %></td>
    <% if pool.isPublic %>
      <td>Public</td>
    <% else %>
      <td>Private</td>
    <% end %>
    <% if !pool.isMember?(current_user) %>
      <td><%= link_to "Join", join_path(pool.id) %></td>
    <% else %>
      <td>Member</td>
    <% end %>
  </tr>

app/views/pools/_pool.html.erb
  <tr>
    <td><%= link_to pool.name, pool %></td>
    <td><%= render 'show_type', :pool => pool %></td>
    <% if pool.isPublic %>
      <td>Public</td>
    <% else %>
      <td>Private</td>
    <% end %>
    <% if !pool.isMember?(current_user) %>
      <% if pool.isOpen? %>
        <td><%= link_to "Join", join_path(pool.id) %></td>
      <% else %>
        <td>Pool Closed<td>
      <% end %>
    <% elsif pool.isOwner?(current_user) %>
      <td>Owner</td>
    <% else %>
      <td>Member</td>
    <% end %>
    <% if current_user.admin? %>
      <td><%= link_to "Diagnostics", pool_diagnostics_path(pool), id: pool.id %></td>
    <% end %>
  </tr>

app/views/pools/_pool_member.html.erb
<li class="list-group-item">
  <% if pool.isOwner?(user) %>
    <%= gravatar_for user, :size => 20 %>
    <small><%= link_to "* #{user.name}", user %></small>
  <% else %>
    <%= gravatar_for user, :size => 20 %>
    <small><%= link_to user.name, user %></small>
  <% end %>
</li>

app/views/pools/_show_survivor_board.html.erb
<!-- Pool information and User pick for current week -->
<h4><u>Picks for week: <%= "#{@current_week.week_number}" %></u></h4>
<% entries = @pool.entries.where(user_id: current_user.id) %>
<% entries.each do |entry| %>
  <b><%= "#{entry.name}:" %></b>&nbsp;
  <% pick = entry.picks.where(entry_id: entry.id, week_id: @current_week.id).first %>
  <% if !pick.nil? %>
    <% game_pick = pick.game_picks.where(pick_id: pick.id).first %>
    <% team_name = Team.find(game_pick.chosenTeamIndex).name %>
    <%= "#{team_name}" %>
    <% if @current_week.open? %>
      <small><%= link_to "[Edit Pick]", edit_pick_path(pick) %></small>
    <% end %>
  <% else %>
    <% if !pool.haveSurvivorWinner? %>
      <% if entry.survivorStatusIn %>
        <% if pool.getCurrentWeek.week_number < pool.starting_week %>
          <%= link_to "Pool has not started yet!", "#" %>
        <% else %> 
          <small><%= link_to "[Make Pick]", new_entry_pick_path(entry) %></small>
        <% end %>
      <% else %>
        Survivor Status: Out of pool
      <% end %>
    <% else %>
      Pool is done!
    <% end %>
  <% end %>
  <br />
<% end %>

<% if pool.haveSurvivorWinner? %>
  <h3>Pool Winner(s)</h3>
  <% winners = pool.getSurvivorWinner %>
  <% if winners.count > 1 %>
    <p> The winners of the pool are:
  <% else %>
    <p> The winner of the pool is:
  <% end %>
  <ul>
    <% winners.each do |entry| %>
      <% user = User.find(entry.user_id) %>
      <li><i><b><%= "#{user.name} (#{entry.name})" %></b></i></li>
    <% end %>
  </ul>
<% end %>

<!-- Show the current board for the pool -->
<h3>Current Board</h3>
<div id="survivor-board" class="table-responsive survivor-board-table">
<table class="table table-striped table-bordered table-condensed table-hover">
  <tr>
    <td class="survivor-board-name"></td>
    <% @season.weeks.order(:week_number).each do |week| %>
      <% if week.week_number >= pool.starting_week %>
        <td class="entry-header"><%= "Week #{week.week_number}" %></td>
      <% end %>
    <% end %>
  </tr>
  <% teams = Team.all.where(nfl: true).order('id ASC') %>
  <% entries = @pool.entries.sort_by {|entry| [entry[:survivorStatusIn] ? 0 : 1,entry[:name]] } %>
  <% entries.each do |entry| %>
    <% entryOut = false %>
    <tr>
      <% if entry.entryStatusGood? %>
        <td class="entry-name"><%= link_to entry.name, user_path(entry.user_id), {class: "entry-name"} %></td>
      <% else %>
        <td class="entry-error"><%= link_to entry.name, user_path(entry.user_id), {class: "entry-name-out"} %></td>
      <% end %>
      <% @season.weeks.order(:week_number).each do |week| %>
        <% if (week.week_number >= pool.starting_week) %>
          <% @picks = entry.picks.where(week_number: week.week_number) %>
          <% if @picks.empty? %> 
            <% if week.checkStateClosed || week.checkStateFinal ||
                  !entry.entryStatusGood? %>
              <% if entryOut %>
                <td class="entry-out">XXX</td>
              <% else %>
                <td class="entry-out">Out</td>
                <% entryOut = true %>
              <% end %>
            <% else %>
              <td class="entry-blank"></td>
            <% end %>
          <% else %>
            <% @picks.each do |pick| %>
              <% game_pick = pick.game_picks.first %>
              <% team_nickname = 
                      teams[game_pick.chosenTeamIndex-1].name.split(" ").last %>
              <% if week.checkStateOpen %>
                <td></td>
              <% else %>
                <% if !week.checkStateFinal %>
                  <td class="entry-base"><%= team_nickname %></td>
                <% else %>
                  <% gameWon = false %>
                  <% week.games.each do |game| %>
                    <% if game.wonGame?(game_pick.chosenTeamIndex) %>
                      <% gameWon = true %>
                    <% end %>
                  <% end %>
                  <% if gameWon %>
                    <td class="entry-success"><%= team_nickname %></td>
                  <% else %>
                    <td class="entry-error"><%= team_nickname %></td>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>
</div>

app/views/pools/_show_type.html.erb
<% if pool.typePickEm? %>
  PickEm
<% elsif pool.typePickEmSpread? %>
  PickEmSpread
<% elsif pool.typeSurvivor? %>
  Survivor
<% elsif pool.typeSUP? %>
  SUP
<% end %>

app/views/pools/edit.html.erb
<% provide(:title, 'Edit pool') %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<h1>Edit Pool</h1>
<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: @pool %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">Edit Pool</div>
        <div class="panel-body">
          <%= simple_form_for @pool, html: { class: 'form-horizontal' },
            wrapper: :horizontal_form,
            wrapper_mappings: {
              check_boxes: :horizontal_radio_and_checkboxes,
              radio_buttons: :horizontal_radio_and_checkboxes,
              file: :horizontal_file_input,
              boolean: :horizontal_boolean
          } do |f| %>
            <%= render 'fields', f: f %>
            <%= f.button :submit, "Save changes", class: "btn btn-large btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pools/index.html.erb
<% provide(:title, 'Pool index') %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<h1>All Pools</h1>

<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: @pool %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">List of All Pools</div>
      <div class="panel-body">
        <% if current_season(1) %>
          <% pools_list = Pool.where(season_id: current_season(1).id) %>
        <% end %>
        <% if pools_list.any? %>
          <%= will_paginate %>
          <table class="table table-striped table-condensed table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Status</th>
                <th>Membership</th>
                <% if current_user.admin? %>
                  <th>Diagnostics</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <%= render @pools %>
            </tbody>
          </table>
          <%= will_paginate %>
        <% else %>
          <p> There are no pools available!</p>
          <%= link_to "Create a pool", new_pool_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pools/my_pools.html.erb
<% provide(:title, 'My Pool index') %>
<h1>My Pools</h1>

<% if current_user.pools.any? %>
<%= will_paginate %>

<div  class="pools">
  <table class="table table-striped 
                table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Status</th>
      <th>Membership</th>
    </tr>
  </thead>
  <tbody>
    <%= render @pools %>
  </tbody>
</table>

<%= will_paginate %>
<% else %>
  <p> There are no pools available!</p>
<% end %>

app/views/pools/new.html.erb
<% provide(:title, 'Create pool') %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<h1>Create Pool</h1>
<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: nil %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">Create New Pool</div>
      <div class="panel-body">
        <%= simple_form_for @pool, html: { class: 'form-horizontal pull-left' },
              wrapper: :horizontal_form,
              wrapper_mappings: {
              check_boxes: :horizontal_radio_and_checkboxes,
              radio_buttons: :horizontal_radio_and_checkboxes,
              file: :horizontal_file_input,
              boolean: :horizontal_boolean
        } do |f| %>
          <%= render 'fields', f: f %>
          <%= f.button :submit, 'Create pool', class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pools/pool_diagnostics.html.erb
<h2> <%= "Pool Diagnostics: #{@pool.name}" %> </h2>
  <h4>
    <b>Pool Status: </b>
    <% if @pool.pool_done %>
      Done
    <% else %>
      Active
    <% end %>
    <small><%= link_to "<Change Pool Status>", pool_diag_chg_path(@pool, pool_status: true, pool_id: @pool.id) %></small>
  </h4>

<% teams = Team.all.where(nfl: true).order('id ASC') %>
<% entries = @pool.entries.sort_by {|entry| [entry[:survivorStatusIn] ? 0 : 1,entry[:name]] } %>
<% entries.each do |entry| %>
  <h4>
    Entry:<%= link_to entry.name, user_path(entry.user_id), {class: "entry-name"} %> <%= "< Id: #{entry.id}>" %>,
    <b>Survivor Status: </b>
    <% if entry.survivorStatusIn %>
      In
    <% else %>
      Out
    <% end %>
    <small><%= link_to "<Change Survivor Status>", pool_diag_chg_path(@pool, surv: true, entry_id: entry.id) %></small>
  </h4>
  <% @season.weeks.order(:week_number).each do |week| %>
    <ul>
      <li><%= "Week: #{week.week_number}" %></li>
      <ul>
        <% @picks = entry.picks.where(week_number: week.week_number) %>
          <% if @picks.empty? %>
            <li> no picks</li>
          <% else %>
            <% @picks.each do |pick| %>
                <% game_pick = pick.game_picks.first %>
                <% if game_pick %>
                  <li>
                    <%= "pick: #{pick.id} game pick: #{game_pick.id}, chosenTeamIndex: #{game_pick.chosenTeamIndex}" %>
                    <% if week.checkStateFinal %>
                      <% gameWon = false %>
                      <% week.games.each do |game| %>
                        <% if game.wonGame?(game_pick.chosenTeamIndex) %>
                          <% gameWon = true %>
                        <% end %>
                      <% end %>
                      <% if gameWon %>
                        <small><%= "(#{teams[game_pick.chosenTeamIndex-1].name}(W)))" %> </small>
                      <% else %>
                        <small><%= "(#{teams[game_pick.chosenTeamIndex-1].name}(L)))" %> </small>
                      <% end %>
                    <% else %>
                      <small><%= "(#{teams[game_pick.chosenTeamIndex-1].name}))" %> </small>
                    <% end %>
                  </li>
                <% end %>
          <% end %>
        <% end %>
      </ul>
    </ul>
  <% end %>
<% end %>

app/views/pools/show.html.erb
<% provide(:title, "Show Pool") %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: @pool %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading"><%= @pool.name %></div>
      <div class="panel-body">
        <strong>Pool Type</strong>
        <%= render 'show_type', pool: @pool %><br />
        <strong>Status</strong>
        <% if @pool.isPublic %>
          Public<br />
        <% else %>
          Private<br />
        <% end %>
        <% if !@current_week.nil? %>
          <strong>Current Week</strong>
          <%= @current_week.week_number %><br />
          <% if @pool.poolType == Pool::POOL_TYPES[:Survivor] %>
            <%= render 'show_survivor_board', pool: @pool, current_week: @current_week %>
          <% elsif @pool.poolType == Pool::POOL_TYPES[:SUP] %>
            <p>Sorry but SUP based pools are not supported at this time.</p>
          <% elsif @pool.poolType == Pool::POOL_TYPES[:PickEm] %>
            <p>Sorry but PickEm based pools are not supported at this time.</p>
          <% elsif @pool.poolType == Pool::POOL_TYPES[:PickEmSpread] %>
            <p>Sorry but PickEmSpread based pools are not supported at this time.</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% if 0 %>
  <!-- >
  <div class="col-md-2">
    <div class="panel panel-primary">
      <div class="panel-heading">Members</div>
      <div class="panel-body">
        <% for user in @pool.users %>
          <ul class="list-group" id="pool-members">
            <%= render 'pool_member', user: user, pool: @pool %>
          </ul->
        <% end %>
      </div>
    </div>
  </div>
  < -->
  <% end %>
</div>