config/routes.rb
FBApps::Application.routes.draw do
  get "password_resets/new"
  resources :users
  resources :teams, only: [:edit, :update, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  # Static routes
  root  'static_pages#home'
  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/help',              to: 'static_pages#help',            via: 'get'
  match '/about',             to: 'static_pages#about',           via: 'get'
  match '/contact',           to: 'static_pages#contact',         via: 'get'
  match 'users/confirm/:confirmation_token', to: 'users#confirm', 
                       as: :confirm,  via: 'get'
  match 'users/resend_confirm/:id',  to: 'users#resend_confirm', 
                       as: :resend_confirm,     via: 'get'
  match 'users/admin_add/:id', to: 'users#admin_add',    
                       as: :admin_add,     via: 'get'
  match 'users/admin_del/:id', to: 'users#admin_del',    
                       as: :admin_del,     via: 'get'


  # Diagnostics paths
  match 'pools/diagnostics/:id',   to: 'pools#pool_diagnostics',   as: :pool_diagnostics,    via: 'get'
  match 'pools/diag_chg/:id',      to: 'pools#pool_diag_chg', as: :pool_diag_chg,    via: 'get'
  match 'seasons/diagnostics/:id', to: 'seasons#season_diagnostics',   as: :season_diagnostics,    via: 'get'
  match 'seasons/diag_chg/:id',    to: 'seasons#season_diag_chg', as: :season_diag_chg,    via: 'get'
  
  # Seasons and weeks paths
  match 'weeks/open/:id',       to: 'weeks#open',        as: :open,          via: 'get'
  match 'weeks/closed/:id',     to: 'weeks#closed',      as: :closed,        via: 'get'
  match 'weeks/final/:id',      to: 'weeks#final',       as: :final,         via: 'get'
  match 'weeks/auto_create',    to: 'weeks#auto_create', as: :auto_create,   via: 'get'
  match 'weeks/add_scores/:id', to: 'weeks#add_scores',  as: :add_scores,    via: 'get'
  match 'seasons/open/:id',     to: 'seasons#open',      as: :season_open,   via: 'get'
  match 'seasons/closed/:id',   to: 'seasons#closed',    as: :season_closed, via: 'get'
  resources :seasons, shallow: :true do
    resources :weeks
  end

  # Pools and Pool Messages routes
  match 'pools/join/:id',     to: 'pools#join',    as: :join,     via: 'get'
  match 'pools/leave/:id',    to: 'pools#leave',   as: :leave,    via: 'get'
  match 'pools/my_pools',     to: 'pools#my_pools',as: :my_pools, via: 'get'
  match 'pools/:id/invite',   to: 'pool_messages#invite',  as: :invite,   via: 'get'
  match 'pools/:id/send_invite',   to: 'pool_messages#send_invite',  as: :send_invite,   via: 'post'
  resources :pools do
    resources :entries, only: [:new, :create]
    resources :pool_messages, only: [:new, :create]
  end
  
  resources :entries, only: [:edit, :update, :destroy] do
    resources :picks, only: [:new, :create]
  end

  resources :weeks, only: [:edit, :update, :show, :destroy]

  resources :picks, only: [:edit, :update, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  user_name              :string(255)
#  email                  :string(255)
#  admin                  :boolean          default(FALSE)
#  supervisor             :boolean          default(FALSE)
#  password_digest        :string(255)
#  remember_token         :string(255)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  confirmed              :boolean          default(FALSE)
#  confirmation_token     :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  has_many :pools, through: :pool_memberships, dependent: :destroy
  has_many :pool_memberships, dependent: :destroy
  has_many :entries, dependent: :delete_all

  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name,  presence: true, length: { :maximum => 50 }
  validates :user_name,  presence: true, length: { :maximum => 15 },
                    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def send_user_confirm
    self.update_attribute(:confirmation_token, create_token)
    UserMailer.confirm_registration(self).deliver_now
  end

  def send_password_reset
    self.update_attribute(:password_reset_token, create_token)
    self.update_attribute(:password_reset_sent_at, Time.zone.now)
    UserMailer.password_reset(self).deliver
  end

  private

    def create_remember_token
      self.remember_token = create_token
    end

    def create_token
      User.encrypt(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :show, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def new
    redirect_to(root_path) unless !signed_in?
    @user = User.new
  end

  def create
    redirect_to(root_path) unless !signed_in?
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save
      sign_in(@user, 0)
      @user.send_user_confirm
      flash[:success] = "Welcome to Football Pool Mania!"
      redirect_to @user
    else
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in(@user, 0)
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def confirm
    @user = User.find_by_confirmation_token!(params[:confirmation_token])
    if @user
      @user.update_attribute(:confirmed, true)
      redirect_to root_url, notice: "User account has been confirmed!"
    else
      render :edit
    end
  end

  def resend_confirm
      if current_user.confirmed?
        redirect_to root_url, notice: "User account has already been confirmed!"
      else
        current_user.send_user_confirm
      redirect_to root_url, notice: "Confirm message has been resent!"
      end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user?(@user)
      flash[:notice] = "You cannot delete yourself!"
    else
      #
      # First we need to delete the pools owned by this user and associated
      # pool memberships
      #
      @user.pools.each do |pool|
        pool.remove_memberships
        pool.recurse_delete
      end
      @user.destroy
      flash[:success] = "User deleted."
    end
    redirect_to users_url
  end
  
  def admin_add
    if current_user.admin? 
      user = User.find(params[:id])
      user.update_attribute(:admin, '1')
      flash[:success] = "Admin status has been granted to User: '#{user.name}!"
    else
      flash[:error] = "Only an Admin user can update admin status!"
    end
    redirect_to users_url
  end
  
  def admin_del
    if current_user.admin? 
      user = User.find(params[:id])
      user.update_attribute(:admin, '0')
      flash[:success] = "Admin status has been removed from User: '#{user.name}!"
    else
      flash[:error] = "Only an Admin user can update admin status!"
    end
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :user_name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_fields.html.erb
  <%= f.error_notification %>

  <%= f.input :name, placeholder: 'Name' %>
  
  <%= f.input :user_name, placeholder: 'User Name' %>

  <%= f.input :email, placeholder: 'Email' %>

  <%= f.input :password, placeholder: 'Password' %>

  <%= f.input :password_confirmation, placeholder: 'Password confirm' %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <% if user.admin? %>
  *&nbsp;
  <% end %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    <% if current_user.supervisor? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
            data: { confirm: "Are you sure?" },
            :title => "Delete #{user.name}" %>
    <% end %>
    <% if !user.supervisor? && !current_user?(user) %>
      <% if user.admin? %>
        | <%= link_to "Delete Admin status", admin_del_path(user.id),
              data: { confirm: "Are you sure?" },
              title: "Delete #{user.name} admin status" %>
      <% else %>
        | <%= link_to "Add Admin status", admin_add_path(user.id),
              data: { confirm: "Are you sure?" },
              title: "Add #{user.name} admin status" %>
      <% end %>
    <% end %>
  <% else %>
    <% if current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
            data: { confirm: "Are you sure?" },
            :title => "Delete #{user.name}" %>
    <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<h1>Update your profile</h1>

<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: @pool %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">Update User Profile</div>
      <div class="panel-body">
        <%= simple_form_for @user, html: { class: 'form-horizontal' },
            wrapper: :horizontal_form,
            wrapper_mappings: {
              check_boxes: :horizontal_radio_and_checkboxes,
              radio_buttons: :horizontal_radio_and_checkboxes,
              file: :horizontal_file_input,
              boolean: :horizontal_boolean
        } do |f| %>
            <%= render 'fields', f: f, edit: 1 %>
            <%= f.button :submit, 'Update Profile', class: "btn btn-large btn-primary" %>
        <% end %>

        <p></p>
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails", target="_blank">change </a>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<!-- Render the season navigation bar -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<h1>All users</h1>

<div class="row">
  <!-- Render the main navigation bar -->
  <%= render 'shared/sidebar_nav', pool: @pool %>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">Create New Pool</div>
      <div class="panel-body">
        <%= will_paginate %>
  
        <ul class="users">
          <%= render @users.sort_by {|u| u.name.downcase} %>
        </ul>

        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading">Create User Account</div>
        <div class="panel-body">
          <%= simple_form_for @user, html: { class: 'form-horizontal' },
            wrapper: :horizontal_form,
            wrapper_mappings: {
              check_boxes: :horizontal_radio_and_checkboxes,
              radio_buttons: :horizontal_radio_and_checkboxes,
              file: :horizontal_file_input,
              boolean: :horizontal_boolean
          } do |f| %>
 
            <%= render 'fields', f: f, edit: 0 %>
            <%= f.button :submit, 'Create my account', class: "btn btn-large btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!-- Render the navigation bars -->
<%= render 'shared/mgmt_weeks_nav', season: current_season(1), week_number: 0 %>

<div class="row">
  <div class="col-sm-4">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
      <small>(<%= link_to @user.email, "#" %>)</small>
    </h1>
  </div>
</div>
<% if !current_user.confirmed? %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 main">
      <p>This user account needs to be confirmed before you can use this site.
        Please look for the email with the subject <i>"Confirm Registration" </i>from
        info@fbpm.com and click the Confirmation URL.  
      </p>
    </div>
  </div>
<% else %>
  <div class="row">
    <!-- Render the main navigation bar -->
    <%= render 'shared/sidebar_nav', pool: nil %>
    <div class="col-sm-8 main">
      <div class="panel panel-primary">
        <div class="panel-heading"><%= "#{@user.name} Profile" %> </div>
        <div class="panel-body">
          <h3>My Pools</h3>
          <ul id="my-pool">
            <% if current_season(1) %>
              <% user_pools = @user.pools.where(season_id: current_season(1).id) %>
            <% end %>
            <% if user_pools && user_pools.any? %>
              <% user_pools.each do |pool| %>
                <li><%= link_to "#{pool.name}", pool %></li>
                <% entries = Entry.where(user_id: @user.id, pool_id: pool.id) %>
                <div class = "table-responsive">
                <table class="table table-striped table-bordered table-condensed table-hover">
                  <tr>
                    <th width="35%">Entry</th>
                    <th width="10%">Week</th>
                    <th width="25%">Survivor Status</th>
                    <% if @user == current_user %>
                      <th width="30%">Current Pick</th>
                    <% end %>
                  </tr>
                  <% entries.each do |entry| %>
                    <tr>
                      <td><%= "#{entry.name}" %></td>
                      <td align="center"><%= current_season(1).current_week %></td>
                      <% if entry.survivorStatusIn %>
                        <td align="center">In</td>
                      <% else %>
                        <td align="center">Out</td>
                      <% end %>
                      <% if @user == current_user %>
                        <% if pool.haveSurvivorWinner? %>
                          <td><%= link_to "Pool is done!", "#" %></td>
                        <% else %>
                          <% pick = Pick.where(entry_id: entry.id,
                              week_id: pool.getCurrentWeek.id).first %>
                          <% if pick %>
                            <% game_pick = pick.game_picks.first %>
                            <td><%= link_to Team.find(game_pick.chosenTeamIndex).name, 
                                    edit_pick_path(pick) %></td>
                          <% else %>
                            <% if pool.getCurrentWeek.week_number < pool.starting_week %>
                              <td><%= link_to "Pool has not started yet!", "#" %></td>
                            <% else %> 
                              <% if entry.survivorStatusIn %>
                                <td><%= link_to "Make picks", new_entry_pick_path(entry) %></td>
                              <% else %>
                                <td>XXX</td>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %> 
                    </tr>
                  <% end %>
                </table>
                </div>
              <% end %>
            <% else %>
              <p>You currently are not a member of any pool for the current Season.  
                <%= link_to "Create", new_pool_path %>
                or
                <%= link_to "Join", pools_path %>
                a pool.
              </p>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>