config/routes.rb
FBApps::Application.routes.draw do
  get "password_resets/new"
  resources :users
  resources :teams, only: [:edit, :update, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  # Static routes
  root  'static_pages#home'
  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/help',              to: 'static_pages#help',            via: 'get'
  match '/about',             to: 'static_pages#about',           via: 'get'
  match '/contact',           to: 'static_pages#contact',         via: 'get'
  match 'users/confirm/:confirmation_token', to: 'users#confirm', 
                       as: :confirm,  via: 'get'
  match 'users/resend_confirm/:id',  to: 'users#resend_confirm', 
                       as: :resend_confirm,     via: 'get'
  match 'users/admin_add/:id', to: 'users#admin_add',    
                       as: :admin_add,     via: 'get'
  match 'users/admin_del/:id', to: 'users#admin_del',    
                       as: :admin_del,     via: 'get'


  # Diagnostics paths
  match 'pools/diagnostics/:id',   to: 'pools#pool_diagnostics',   as: :pool_diagnostics,    via: 'get'
  match 'pools/diag_chg/:id',      to: 'pools#pool_diag_chg', as: :pool_diag_chg,    via: 'get'
  match 'seasons/diagnostics/:id', to: 'seasons#season_diagnostics',   as: :season_diagnostics,    via: 'get'
  match 'seasons/diag_chg/:id',    to: 'seasons#season_diag_chg', as: :season_diag_chg,    via: 'get'
  
  # Seasons and weeks paths
  match 'weeks/open/:id',       to: 'weeks#open',        as: :open,          via: 'get'
  match 'weeks/closed/:id',     to: 'weeks#closed',      as: :closed,        via: 'get'
  match 'weeks/final/:id',      to: 'weeks#final',       as: :final,         via: 'get'
  match 'weeks/auto_create',    to: 'weeks#auto_create', as: :auto_create,   via: 'get'
  match 'weeks/add_scores/:id', to: 'weeks#add_scores',  as: :add_scores,    via: 'get'
  match 'seasons/open/:id',     to: 'seasons#open',      as: :season_open,   via: 'get'
  match 'seasons/closed/:id',   to: 'seasons#closed',    as: :season_closed, via: 'get'
  resources :seasons, shallow: :true do
    resources :weeks
  end

  # Pools and Pool Messages routes
  match 'pools/join/:id',     to: 'pools#join',    as: :join,     via: 'get'
  match 'pools/leave/:id',    to: 'pools#leave',   as: :leave,    via: 'get'
  match 'pools/my_pools',     to: 'pools#my_pools',as: :my_pools, via: 'get'
  match 'pools/:id/invite',   to: 'pool_messages#invite',  as: :invite,   via: 'get'
  match 'pools/:id/send_invite',   to: 'pool_messages#send_invite',  as: :send_invite,   via: 'post'
  resources :pools do
    resources :entries, only: [:new, :create]
    resources :pool_messages, only: [:new, :create]
  end
  
  resources :entries, only: [:edit, :update, :destroy] do
    resources :picks, only: [:new, :create]
  end

  resources :weeks, only: [:edit, :update, :show, :destroy]

  resources :picks, only: [:edit, :update, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_games.html.erb
<table class = "table table-condensed">
  <tbody>
    <% prev_game = nil %>
    <% games.order(:game_date).each do |game| %>
      <% if game.game_date %>
        <% gameDate = game.game_date.strftime("%A, %b %d") %>
        <% gameTime = game.game_date.strftime("%l:%M %p %Z") %>
        <% if (!prev_game || (game.game_date.strftime("%A, %b %d") != prev_game.game_date.strftime("%A, %b %d"))) %>
          <tr> <td class="gameDate"><%= gameDate %> </td> </tr>
        <% end %>
      <% end %>
      <tr>
          <% team = Team.find(game.awayTeamIndex) %>
          <% awayTeamWon = game.wonGame?(game.awayTeamIndex) %>
          <% if awayTeamWon && !(game.awayTeamScore == 0 && game.homeTeamScore == 0) %>
            <td class="awayTeamWon">
              <b><%= team.name.split(' ').last.upcase %></b>
              <%= image_tag(asset_path(team.imagePath), size: "40x30") %>
            </td>
            <% if showScores %>
              <td class="awayScoreWon"><b><%= game.awayTeamScore %></b></td>
            <% end %>
          <% else %>
            <td class="awayTeamLost">
              <%= team.name.split(' ').last.upcase %>
              <%= image_tag(asset_path(team.imagePath), size: "40x30") %>
            </td>
            <% if showScores %>
              <td class="awayScoreLost"><%= game.awayTeamScore %></td>
            <% end %>
          <% end %>
        <% if !showScores %>
          <td class="gameDescriptor"><small>AT</small></td>
        <% end %>
          <% team = Team.find(game.homeTeamIndex) %>
          <% homeTeamWon = game.wonGame?(game.homeTeamIndex) %>
          <% if homeTeamWon && !(game.awayTeamScore == 0 && game.homeTeamScore == 0) %>
            <% if showScores %>
              <td class="homeScoreWon"><b><%= game.homeTeamScore %></b></td>
            <% end %>
            <td class="homeTeamWon">
              <%= image_tag(asset_path(team.imagePath), size: "40x30") %>
              <b><%= team.name.split(' ').last.upcase %></b>
            </td>
          <% else %>
            <% if showScores %>
              <td class="homeScoreLost"><%= game.homeTeamScore %></td>
            <% end %>
            <td class="homeTeamLost">
              <%= image_tag(asset_path(team.imagePath), size: "40x30") %>
              <%= team.name.split(' ').last.upcase %>
            </td>
          <% end %>
      </tr>
      <% prev_game = game %>
    <% end %>
  </tbody>
</table>

app/views/shared/_mgmt_pools_nav.html.erb
<% if pool && pool.isOwner?(current_user) %>
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown"
      href="#" > Pool Messages <b class="caret"></b> </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Invite people to join", invite_path(@pool.id) %></li>
    <li><%= link_to "Send group message", new_pool_pool_message_path(pool) %></li>
  </ul>
</li>
<% end %>

<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown"
      href="#" > Manage Pool <b class="caret"></b> </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Create new pool", new_pool_path %></li>
    <li><%= link_to "Show all pools", pools_path %></li>
    <% if pool && pool.isOwner?(current_user) %>
      <li><%= link_to "Edit pool", edit_pool_path(pool) %></li>
      <li><%= link_to "Delete pool", pool, method: :delete,
          data: {confirm: "Are you sure?"}, title: "Delete#{pool.name}" %> </li>
      <li><%= link_to "Send Group Message", new_pool_pool_message_path(pool) %>
    <% end %>
  </ul>
</li>
<% if pool && !pool.isOwner?(current_user) %>
  <% if pool.isMember?(current_user) %>
    <% if pool.isOpen? %>
      <li><%= link_to "Leave Pool", leave_path(pool.id), id: pool.id %></li>
    <% end %>
  <% else %>
    <% if pool.isOpen? %>
      <li><%= link_to "Join Pool", join_path(pool.id), id: pool.id %></li>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_mgmt_weeks_nav.html.erb
<nav class="navbar navbar-default weeks-nav" role="navigation">
  <div class="container">
    <div class="btn-group-sm">
      <% if current_season(1) %>
        <% if current_user.admin? %>
          <%= link_to "Season #{season.year}", season_path(season), :class => "btn btn-primary",
                           :role => "button" %>
          <% if season.weeks.count < season.number_of_weeks %>
            <%= link_to "Create new week", new_season_week_path(season), :class => "btn btn-primary",
                           :role => "button" %>
          <% end %>
        <% else %>
          <%= link_to "Season #{season.year}", "#", :class => "btn btn-primary",
                           :role => "button" %>
        <% end %>
        <%= link_to "Week:", "#", :class => "btn btn-primary",
                         :role => "button" %>
        <% if season.weeks.any? %>
          <% season.weeks.order(:week_number).each do |week| %>
            <% if week.week_number == week_number %>
              <%= link_to "#{week.week_number}", "#", :class => "btn btn-default",
                           :role => "button" %>
            <% else %>
              <%= link_to "#{week.week_number}", week_path(week), :class => "btn btn-primary",
                           :role => "button" %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to "Create new season", new_season_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_show_week_state.html.erb
<% if week.checkStatePend %>
Pending
<% elsif week.checkStateOpen %>
Open
<% elsif week.checkStateClosed %>
Closed
<% else %>
Final
<% end %>

app/views/shared/_show_week_state_btn.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-default btn-primary dropdown-toggle" data-toggle="dropdown">
    <%= "Change Week: #{week.week_number} State" %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% if week %>
      <% if week.checkStatePend || week.checkStateClosed %>
        <li><%= link_to "Mark week open", open_path(week) %></li>
      <% end %>
      <% if week.checkStateOpen %>
        <li><%= link_to "Mark week closed", closed_path(week) %></li>
      <% end %>
      <% if week.checkStateClosed %>
        <li><%= link_to "Mark week final", final_path(week) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_sidebar_nav.html.erb
<div class="col-sm-2">
  <!-- div class="panel panel-primary" -->
  <div class="panel panel-default">
    <div class="panel-heading">Navigation </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to '<i class="fa fa-user fa-fw"></i>All Users'.html_safe, users_path %></li>
        <li><%= link_to '<i class="fa fa-user fa-fw"></i>Profile'.html_safe, current_user %></li>
        <% if current_season(1) %>
          <% user_pools = current_user.pools.where(season_id: current_season(1).id) %>
        <% end %>
        <% if user_pools && user_pools.any? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              My Pools <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% user_pools.each do |pool| %>
                <% if pool.id %>
                  <li><%= link_to "#{pool.name}", pool_path(pool) %></li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li class="divider"></li>
        <%= render 'shared/mgmt_pools_nav', pool: pool %>
        <% if pool %>
          <% if pool.typeSurvivor? %>
            <%= render 'pools/entry_mgmt_menu', pool: pool, current_week: pool.getCurrentWeek %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>